version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: puppeteer
    versions:
    - 5.5.0
    - 6.0.0
    - 7.0.0
    - 7.0.1
    - 7.0.4
    - 7.1.0
    - 8.0.0
  - dependency-name: codemod-cli
    versions:
    - 3.1.1
